package MODEL;

public class ConsultasSQL {
    // --- PRODUCTO ---
    public static final String PROD_INSERT = "INSERT INTO PRODUCTO (IDPRODUCTO, NOMBREPRODUCTO, DESCRIPCION, PRECIO, STOCK) VALUES (?, ?, ?, ?, ?)";
    public static final String PROD_SELECT_ALL = "SELECT * FROM PRODUCTO";
    public static final String PROD_UPDATE = "UPDATE PRODUCTO SET NOMBREPRODUCTO=?, DESCRIPCION=?, PRECIO=?, STOCK=? WHERE IDPRODUCTO=?";
    public static final String PROD_DELETE = "DELETE FROM PRODUCTO WHERE IDPRODUCTO=?";
    public static final String PROD_PRECIO = "SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = ?";
    public static final String PROD_STOCK = "SELECT STOCK FROM PRODUCTO WHERE IDPRODUCTO = ?";
    public static final String PROD_ID_NOMBRE = "SELECT IDPRODUCTO, NOMBREPRODUCTO FROM PRODUCTO";

    // --- CLIENTE ---
    public static final String CLI_INSERT = "INSERT INTO CLIENTE (IDCLIENTE, NOMBRECLIENTE, APELLIDOCLIENTE, TELEFONO, DIRECCION) VALUES (?, ?, ?, ?, ?)";
    public static final String CLI_SELECT_ALL = "SELECT * FROM CLIENTE";
    public static final String CLI_UPDATE = "UPDATE CLIENTE SET NOMBRECLIENTE=?, APELLIDOCLIENTE=?, TELEFONO=?, DIRECCION=? WHERE IDCLIENTE=?";
    public static final String CLI_DELETE = "DELETE FROM CLIENTE WHERE IDCLIENTE=?";
    public static final String CLI_ID_NOMBRE = "SELECT IDCLIENTE, NOMBRECLIENTE FROM CLIENTE";

    // --- VENTA ---
    public static final String VTA_INSERT = "INSERT INTO VENTA (IDVENTA, FECHAVENTA, TOTAL) VALUES (?, ?, ?)";
    public static final String VTA_LOCK = "SELECT STOCK, PRECIO FROM PRODUCTO WHERE IDPRODUCTO=? FOR UPDATE";
    public static final String VTA_INSERT_DET = "INSERT INTO DETALLEVENTA (IDDETALLE, IDVENTA, IDPRODUCTO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL) VALUES (?, ?, ?, ?, ?, ?)";
    public static final String VTA_UPD_STOCK = "UPDATE PRODUCTO SET STOCK = STOCK - ? WHERE IDPRODUCTO=?";
    public static final String VTA_SELECT_ALL = "SELECT IDVENTA, FECHAVENTA, TOTAL FROM VENTA ORDER BY CAST(SUBSTRING(IDVENTA, 2) AS UNSIGNED) ASC";
    public static final String VTA_DETALLES = "SELECT D.IDDETALLE, D.IDPRODUCTO, P.NOMBREPRODUCTO, D.CANTIDAD, D.PRECIO_UNITARIO, D.SUBTOTAL FROM DETALLEVENTA D JOIN PRODUCTO P ON D.IDPRODUCTO = P.IDPRODUCTO WHERE D.IDVENTA = ?";
    public static final String VTA_DEL_DET1 = "DELETE FROM DETALLEVENTA WHERE IDVENTA = ?";
    public static final String VTA_DEL_VTA1 = "DELETE FROM VENTA WHERE IDVENTA = ?";
    public static final String VTA_DEL_DET = "DELETE FROM DETALLEVENTA WHERE IDVENTA = ?";
    public static final String VTA_DEL_VTA = "DELETE FROM VENTA WHERE IDVENTA = ?";
}